version: '2'
services:
  servicefacade:
    build:
      context: .
      dockerfile: DockerFile.SF
    container_name: service_facade
    ports:
      - "36001:35000"
    depends_on:
      - log_service_rr1
      - log_service_rr2
      - log_service_rr3
  log_service_rr1:
    build:
      context: .
      dockerfile: DockerFile.RR1
    container_name: log_service_rr1
    ports:
      - "36002:37000"
    depends_on:
      - db
  log_service_rr2:
    build:
      context: .
      dockerfile: DockerFile.RR2
    container_name: log_service_rr2
    ports:
      - "36003:38000"
    depends_on:
      - db
  log_service_rr3:
    build:
      context: .
      dockerfile: DockerFile.RR3
    container_name: log_service_rr3
    ports:
      - "36004:39000"
    depends_on:
      - db
  db:
    image: mongo:4.4.6-bionic
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod

volumes:
  mongodb:
  mongodb_config: